
[workspace]
resolver = "3"
members = [
    "crates/framework",
    "crates/common",
    # "crates/common-export",
    "crates/desktop",
    "crates/desktop-export",
    "crates/desktop-import",
    "crates/egl",
    "crates/gl",
    "crates/render",
    # "crates/render-export",
    # "crates/render-import",
    "crates/text",
    # "crates/widget",
    "crates/xtask",
]

[workspace.package]
version = "0.1.0"
authors = ["foxcirc"]
edition = "2024"
