
[workspace]
resolver = "3"
members = [
    "crates/xtask",
    "crates/showcase",
    "crates/framework",
    "crates/common",
    "crates/futures",
    "crates/desktop",
    "crates/egl",
    "crates/gl",
    "crates/render",
    "crates/text",
]

[workspace.package]
version = "0.1.0"
authors = ["foxcirc"]
edition = "2024"
