[package]
name = "showcase"

version.workspace = true
authors.workspace = true
edition.workspace = true

[features]
default = []
linux = ["desktop/linux", "render/gl", "futures/linux"]
browser = ["desktop/browser", "render/browser", "futures/browser"]

[dependencies]
common = { path = "../common" }
desktop = { path = "../desktop" }
futures = { path = "../futures" }
render = { path = "../render" }
graphics = { path = "../graphics" }
