[package]
name = "graphics"

version.workspace = true
authors.workspace = true
edition.workspace = true

[features]
export = []
import = []

[dependencies]
common = { path = "../common" }
gl = { path = "../gl" }

# On following platforms EGL is used to load OpenGL: Linux, Windows, Android
[target.'cfg(all(not(feature = "import"), any(target_os = "linux", target_os = "windows", target_os = "android")))'.dependencies]
egl = { path = "../egl" }
