[package]
name = "graphics"

version.workspace = true
authors.workspace = true
edition.workspace = true

[features]
default = ["gl"]
import  = []
browser = ["import"]
gl      = ["dep:gl", "dep:egl"]

[dependencies]
common = { path = "../common" }
gl = { path = "../gl", optional = true }
egl = { path = "../egl", optional = true }
