[package]
name = "lsg-window"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
memmap = "0.7.0"
wayland-client = "0.31.2"
wayland-protocols = { version = "0.31.2", features = ["client"] }
