[package]
name = "lsg-window"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
wayland-client = "0.31.2"
wayland-protocols = { version = "0.31.2", features = ["client"] }
wayland-egl = "0.32.0"
khronos-egl = { version = "6.0.0", features = ["static"] }
