
[package]
name = "lsg"
description = "light and small gui apps"

version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
common = { path = "../common" }

[target.'cfg(target_os = "linux")'.dependencies]
desktop = { path = "../desktop" }
render = { path = "../render" }
graphics = { path = "../graphics" }
text = { path = "../text" }
widget = { path = "../widget" }

futures-lite = "2.6.1"
async-executor = "1.13.3"

[target.'cfg(target_family = "wasm")'.dependencies]
desktop = { path = "../desktop", features = ["import"] }
