[package]
name = "text"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
common = { path = "../common" }
# font rendering
swash = { version = "0.2.0", default-features = false }
skrifa = { version = "0.26.5", default-features = false }
